name: Django CI/CD

on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Pull Latest Code
        run: |
          cd C:\Users\ASUS\test\simple-django-app\cool_counters
          git pull origin main

      - name: Run Migrations
        run: |
          cd C:\Users\ASUS\test\simple-django-app\cool_counters
          python manage.py migrate
